# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elo_data',
            fields=[
                ('id', models.AutoField(verbose_name='ID', auto_created=True, serialize=False, primary_key=True)),
                ('team', models.TextField(default='')),
                ('elo', models.IntegerField(default=0)),
                ('finish_1', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_2', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_3', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_4', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_5', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_6', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_7', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_8', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_9', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_10', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_11', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_12', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_13', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_14', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_15', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_16', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('elo_min0', models.IntegerField(default=0)),
                ('elo_min1', models.IntegerField(default=0)),
                ('elo_min2', models.IntegerField(default=0)),
                ('elo_min3', models.IntegerField(default=0)),
                ('elo_min4', models.IntegerField(default=0)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='elo_data_po',
            fields=[
                ('id', models.AutoField(verbose_name='ID', auto_created=True, serialize=False, primary_key=True)),
                ('team', models.TextField(default='')),
                ('finish_1', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_2', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_3', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_4', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_5', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_6', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_7', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_8', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_9', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_10', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_11', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_12', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_13', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_14', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_15', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_16', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='game_data',
            fields=[
                ('id', models.AutoField(verbose_name='ID', auto_created=True, serialize=False, primary_key=True)),
                ('game_date', models.DateField()),
                ('game_hour', models.TextField(default='')),
                ('host', models.TextField(default='')),
                ('visitor', models.TextField(default='')),
                ('played', models.TextField(default='')),
                ('host_goal', models.TextField(default='')),
                ('visitor_goal', models.TextField(default='')),
                ('result', models.TextField(default='')),
                ('referee', models.TextField(default='')),
                ('stadium', models.TextField(default='')),
                ('spectators', models.TextField(default='')),
                ('host_goal_data', models.TextField(default='')),
                ('visitor_goal_data', models.TextField(default='')),
                ('host_yellow_card_data', models.TextField(default='')),
                ('visitor_yellow_card_data', models.TextField(default='')),
                ('host_red_card_data', models.TextField(default='')),
                ('visitor_red_card_data', models.TextField(default='')),
                ('host_starting_team', models.TextField(default='')),
                ('visitor_starting_team', models.TextField(default='')),
                ('host_substitution', models.TextField(default='')),
                ('visitor_substitution', models.TextField(default='')),
                ('host_manager', models.TextField(default='')),
                ('visitor_manager', models.TextField(default='')),
                ('host_elo', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('tie_elo', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('visitor_elo', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('host_spi', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('tie_spi', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('visitor_spi', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('upset', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('excitement', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_1', models.IntegerField(default=0)),
                ('minute_1_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_1_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_1_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_2', models.IntegerField(default=0)),
                ('minute_2_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_2_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_2_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_3', models.IntegerField(default=0)),
                ('minute_3_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_3_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_3_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_4', models.IntegerField(default=0)),
                ('minute_4_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_4_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_4_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_5', models.IntegerField(default=0)),
                ('minute_5_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_5_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_5_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_6', models.IntegerField(default=0)),
                ('minute_6_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_6_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_6_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_7', models.IntegerField(default=0)),
                ('minute_7_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_7_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_7_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_8', models.IntegerField(default=0)),
                ('minute_8_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_8_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_8_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_9', models.IntegerField(default=0)),
                ('minute_9_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_9_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_9_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_10', models.IntegerField(default=0)),
                ('minute_10_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_10_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_10_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_11', models.IntegerField(default=0)),
                ('minute_11_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_11_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_11_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_12', models.IntegerField(default=0)),
                ('minute_12_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_12_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_12_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_13', models.IntegerField(default=0)),
                ('minute_13_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_13_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_13_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_14', models.IntegerField(default=0)),
                ('minute_14_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_14_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_14_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_15', models.IntegerField(default=0)),
                ('minute_15_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_15_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_15_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_16', models.IntegerField(default=0)),
                ('minute_16_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_16_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_16_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_17', models.IntegerField(default=0)),
                ('minute_17_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_17_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_17_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_18', models.IntegerField(default=0)),
                ('minute_18_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_18_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_18_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_19', models.IntegerField(default=0)),
                ('minute_19_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_19_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_19_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_20', models.IntegerField(default=0)),
                ('minute_20_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_20_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_20_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_21', models.IntegerField(default=0)),
                ('minute_21_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_21_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_21_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_22', models.IntegerField(default=0)),
                ('minute_22_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_22_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_22_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_23', models.IntegerField(default=0)),
                ('minute_23_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_23_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_23_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_24', models.IntegerField(default=0)),
                ('minute_24_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_24_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_24_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_25', models.IntegerField(default=0)),
                ('minute_25_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_25_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_25_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_26', models.IntegerField(default=0)),
                ('minute_26_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_26_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_26_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_27', models.IntegerField(default=0)),
                ('minute_27_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_27_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_27_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_28', models.IntegerField(default=0)),
                ('minute_28_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_28_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_28_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_29', models.IntegerField(default=0)),
                ('minute_29_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_29_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_29_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_30', models.IntegerField(default=0)),
                ('minute_30_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_30_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_30_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_31', models.IntegerField(default=0)),
                ('minute_31_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_31_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_31_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_32', models.IntegerField(default=0)),
                ('minute_32_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_32_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_32_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_33', models.IntegerField(default=0)),
                ('minute_33_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_33_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_33_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_34', models.IntegerField(default=0)),
                ('minute_34_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_34_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_34_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_35', models.IntegerField(default=0)),
                ('minute_35_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_35_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_35_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_36', models.IntegerField(default=0)),
                ('minute_36_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_36_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_36_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_37', models.IntegerField(default=0)),
                ('minute_37_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_37_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_37_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_38', models.IntegerField(default=0)),
                ('minute_38_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_38_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_38_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_39', models.IntegerField(default=0)),
                ('minute_39_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_39_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_39_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_40', models.IntegerField(default=0)),
                ('minute_40_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_40_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_40_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_41', models.IntegerField(default=0)),
                ('minute_41_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_41_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_41_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_42', models.IntegerField(default=0)),
                ('minute_42_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_42_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_42_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_43', models.IntegerField(default=0)),
                ('minute_43_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_43_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_43_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_44', models.IntegerField(default=0)),
                ('minute_44_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_44_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_44_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_45', models.IntegerField(default=0)),
                ('minute_45_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_45_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_45_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_46', models.IntegerField(default=0)),
                ('minute_46_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_46_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_46_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_47', models.IntegerField(default=0)),
                ('minute_47_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_47_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_47_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_48', models.IntegerField(default=0)),
                ('minute_48_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_48_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_48_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_49', models.IntegerField(default=0)),
                ('minute_49_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_49_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_49_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_50', models.IntegerField(default=0)),
                ('minute_50_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_50_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_50_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_51', models.IntegerField(default=0)),
                ('minute_51_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_51_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_51_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_52', models.IntegerField(default=0)),
                ('minute_52_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_52_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_52_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_53', models.IntegerField(default=0)),
                ('minute_53_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_53_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_53_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_54', models.IntegerField(default=0)),
                ('minute_54_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_54_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_54_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_55', models.IntegerField(default=0)),
                ('minute_55_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_55_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_55_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_56', models.IntegerField(default=0)),
                ('minute_56_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_56_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_56_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_57', models.IntegerField(default=0)),
                ('minute_57_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_57_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_57_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_58', models.IntegerField(default=0)),
                ('minute_58_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_58_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_58_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_59', models.IntegerField(default=0)),
                ('minute_59_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_59_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_59_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_60', models.IntegerField(default=0)),
                ('minute_60_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_60_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_60_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_61', models.IntegerField(default=0)),
                ('minute_61_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_61_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_61_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_62', models.IntegerField(default=0)),
                ('minute_62_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_62_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_62_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_63', models.IntegerField(default=0)),
                ('minute_63_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_63_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_63_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_64', models.IntegerField(default=0)),
                ('minute_64_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_64_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_64_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_65', models.IntegerField(default=0)),
                ('minute_65_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_65_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_65_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_66', models.IntegerField(default=0)),
                ('minute_66_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_66_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_66_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_67', models.IntegerField(default=0)),
                ('minute_67_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_67_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_67_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_68', models.IntegerField(default=0)),
                ('minute_68_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_68_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_68_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_69', models.IntegerField(default=0)),
                ('minute_69_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_69_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_69_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_70', models.IntegerField(default=0)),
                ('minute_70_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_70_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_70_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_71', models.IntegerField(default=0)),
                ('minute_71_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_71_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_71_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_72', models.IntegerField(default=0)),
                ('minute_72_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_72_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_72_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_73', models.IntegerField(default=0)),
                ('minute_73_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_73_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_73_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_74', models.IntegerField(default=0)),
                ('minute_74_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_74_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_74_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_75', models.IntegerField(default=0)),
                ('minute_75_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_75_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_75_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_76', models.IntegerField(default=0)),
                ('minute_76_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_76_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_76_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_77', models.IntegerField(default=0)),
                ('minute_77_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_77_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_77_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_78', models.IntegerField(default=0)),
                ('minute_78_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_78_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_78_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_79', models.IntegerField(default=0)),
                ('minute_79_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_79_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_79_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_80', models.IntegerField(default=0)),
                ('minute_80_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_80_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_80_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_81', models.IntegerField(default=0)),
                ('minute_81_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_81_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_81_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_82', models.IntegerField(default=0)),
                ('minute_82_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_82_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_82_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_83', models.IntegerField(default=0)),
                ('minute_83_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_83_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_83_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_84', models.IntegerField(default=0)),
                ('minute_84_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_84_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_84_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_85', models.IntegerField(default=0)),
                ('minute_85_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_85_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_85_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_86', models.IntegerField(default=0)),
                ('minute_86_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_86_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_86_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_87', models.IntegerField(default=0)),
                ('minute_87_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_87_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_87_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_88', models.IntegerField(default=0)),
                ('minute_88_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_88_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_88_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_89', models.IntegerField(default=0)),
                ('minute_89_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_89_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_89_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_90', models.IntegerField(default=0)),
                ('minute_90_host', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_90_tie', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('minute_90_visitor', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='spi_data',
            fields=[
                ('id', models.AutoField(verbose_name='ID', auto_created=True, serialize=False, primary_key=True)),
                ('team', models.TextField(default='')),
                ('spi', models.DecimalField(max_digits=65, default=0, decimal_places=2)),
                ('off_rating', models.DecimalField(max_digits=65, default=0, decimal_places=2)),
                ('def_rating', models.DecimalField(max_digits=65, default=0, decimal_places=2)),
                ('finish_1', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_2', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_3', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_4', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_5', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_6', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_7', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_8', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_9', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_10', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_11', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_12', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_13', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_14', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_15', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
                ('finish_16', models.DecimalField(max_digits=30, default=0, decimal_places=15)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='standings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', auto_created=True, serialize=False, primary_key=True)),
                ('rank', models.IntegerField(default=0)),
                ('team', models.TextField(default='')),
                ('games', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('tie', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
